use crate::context::ContextFileContent;
use serde::{Deserialize, Serialize};
use tauqe_protocol::{Plan, PlanItem, PlanItemStatus};

/// Formats the plan and its items into a prompt block for LLM context.
pub fn format_active_plan_context(plan: &Plan) -> Option<String> {
    if plan.items.is_empty() {
        return None;
    }

    let (total, completed) = plan.count_stats();
    let mut out = String::new();
    out.push_str(&format!(
        "<active_plan id=\"{}\" title=\"{}\" progress=\"{}/{} completed\">\n",
        plan.id, plan.title, completed, total
    ));

    if let Some(desc) = &plan.description {
        out.push_str(&format!("  <description>{}</description>\n", desc.trim()));
    }

    fn render_items(out: &mut String, items: &[PlanItem], depth: usize) {
        let indent = "  ".repeat(depth + 1);
        for item in items {
            let status_mark = match item.status {
                PlanItemStatus::Discussion => "DISCUSSION",
                PlanItemStatus::Todo => "TODO",
                PlanItemStatus::InProgress => "IN_PROGRESS",
                PlanItemStatus::Done => "DONE",
                PlanItemStatus::Cancelled => "CANCELLED",
            };

            out.push_str(&format!(
                "{}- {} (id: \"{}\", status: {})",
                indent, item.title, item.id, status_mark
            ));

            if let Some(details) = &item.details {
                let trimmed = details.trim();
                if !trimmed.is_empty() {
                    out.push_str(&format!(": {}", trimmed));
                }
            }
            out.push('\n');

            if !item.children.is_empty() {
                render_items(out, &item.children, depth + 1);
            }
        }
    }

    render_items(&mut out, &plan.items, 0);
    out.push_str("</active_plan>");

    Some(out)
}

/// Output of deep plan refinement generated by the architect model.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlanRefinementOutput {
    pub status: String,
    pub explanation: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub context_requests: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub items: Vec<PlanItem>,
}

/// Parses the raw JSON string returned by the model into a `PlanRefinementOutput`.
pub fn parse_plan_refinement_output(raw_json: &str) -> anyhow::Result<PlanRefinementOutput> {
    let trimmed = raw_json.trim();
    let cleaned = trimmed
        .strip_prefix("```json")
        .or_else(|| trimmed.strip_prefix("```"))
        .unwrap_or(trimmed);
    let cleaned = cleaned
        .strip_suffix("```")
        .unwrap_or(cleaned)
        .trim();
    serde_json::from_str(cleaned)
        .map_err(|e| anyhow::anyhow!("Failed to parse plan refinement JSON output: {e}"))
}

/// Maximum supported hierarchy nesting depth for structured plan refinement output.
pub const MAX_PLAN_REFINEMENT_DEPTH: usize = 5;

/// Helper that builds an unrolled, non-recursive PlanItem JSON Schema up to `max_depth`.
fn plan_item_schema(depth: usize, max_depth: usize) -> serde_json::Value {
    let mut properties = serde_json::Map::new();
    properties.insert(
        "id".to_string(),
        serde_json::json!({
            "type": "string",
            "description": "Step identifier (e.g. '1', '1.1', '2')"
        }),
    );
    properties.insert(
        "title".to_string(),
        serde_json::json!({
            "type": "string",
            "description": "Concise step title formulated strictly in the same natural language as the plan description"
        }),
    );
    properties.insert(
        "details".to_string(),
        serde_json::json!({
            "anyOf": [
                { "type": "string" },
                { "type": "null" }
            ],
            "description": "Concrete technical details in the same language as the plan description: target files, functions, contracts, verification criteria"
        }),
    );
    properties.insert(
        "status".to_string(),
        serde_json::json!({
            "type": "string",
            "enum": ["discussion", "todo", "in_progress", "done", "cancelled"],
            "description": "Step status"
        }),
    );

    let mut required = vec![
        serde_json::Value::String("id".to_string()),
        serde_json::Value::String("title".to_string()),
        serde_json::Value::String("details".to_string()),
        serde_json::Value::String("status".to_string()),
    ];

    if depth < max_depth {
        properties.insert(
            "children".to_string(),
            serde_json::json!({
                "type": "array",
                "description": "Sub-steps or child items",
                "items": plan_item_schema(depth + 1, max_depth)
            }),
        );
        required.push(serde_json::Value::String("children".to_string()));
    }

    serde_json::json!({
        "type": "object",
        "description": if depth < max_depth {
            "A refined step or item in the plan"
        } else {
            "A leaf step at maximum hierarchy depth (cannot have children)"
        },
        "properties": properties,
        "required": required,
        "additionalProperties": false
    })
}

/// Strict JSON Schema for deep plan refinement output.
///
/// Unrolls nested plan items up to `MAX_PLAN_REFINEMENT_DEPTH` (5 levels) to guarantee
/// compliance with LLM Structured Output engines that forbid recursive `$ref` schemas.
pub fn plan_refine_response_schema() -> serde_json::Value {
    serde_json::json!({
        "type": "object",
        "properties": {
            "status": {
                "type": "string",
                "enum": ["success", "blocked", "needs_context"],
                "description": "Result status: 'success' if the plan was refined into actionable steps, 'blocked' if architectural blockers exist, or 'needs_context' if specific source files from repo_map must be inspected before designing the roadmap."
            },
            "explanation": {
                "type": "string",
                "description": "Architectural breakdown, decomposition strategy, dependency analysis, and technical rationale strictly in the same language as the plan description."
            },
            "reason": {
                "anyOf": [
                    { "type": "string" },
                    { "type": "null" }
                ],
                "description": "Required when status is 'blocked': detailed technical explanation in the same language as the plan description of the contradiction, missing prerequisite, or codebase blocker."
            },
            "context_requests": {
                "type": "array",
                "description": "Required when status is 'needs_context': repository-relative file paths from <repo_map> that need to be read to verify contracts and inspect implementation details.",
                "items": {
                    "type": "string",
                    "description": "Repository-relative file path"
                }
            },
            "items": {
                "type": "array",
                "description": "Refined hierarchical list of plan items (up to 5 levels of nesting). If status is 'blocked' or 'needs_context', this must be empty.",
                "items": plan_item_schema(1, MAX_PLAN_REFINEMENT_DEPTH)
            }
        },
        "required": ["status", "explanation", "reason", "context_requests", "items"],
        "additionalProperties": false
    })
}

/// JSON Schema definition wrapper for provider configuration.
pub fn plan_refine_response_schema_definition() -> serde_json::Value {
    serde_json::json!({
        "name": "plan_refinement",
        "description": "Deep plan refinement output: decomposition into actionable steps or blocker report",
        "strict": true,
        "schema": plan_refine_response_schema()
    })
}

/// Builds the system prompt for deep plan refinement (Principal Architect).
pub fn build_plan_refine_system_prompt(_plan: &Plan) -> String {
    let mut out = String::new();
    out.push_str("You are a Principal Software Architect in TAUQE (The Answer to the Ultimate Question of Engineering).\n\n");
    out.push_str("Your mission is Deep Plan Refinement: converting an established architectural objective into a rigorous, production-grade engineering roadmap.\n\n");

    out.push_str("## Core Invariants & Rules:\n\n");
    out.push_str("1. Strict Prohibition of Conceptual Drift (\"How\" vs \"What\"):\n");
    out.push_str("   - The developer has already defined the conceptual intent, architectural direction, and scope (\"What\").\n");
    out.push_str("   - You MUST NOT alter, expand, dilute, or contradict the core intent of the plan.\n");
    out.push_str("   - Your exclusive responsibility is engineering decomposition (\"How\"): determining the exact modules, interfaces, contracts, types, and sequence of implementation.\n\n");
    out.push_str("2. Strict Blocker Protocol (Refusal to Plan):\n");
    out.push_str("   - If you discover an insurmountable contradiction, technical blocker, missing prerequisite, or flawed assumption in the codebase or plan requirements:\n");
    out.push_str("   - You MUST NOT invent a compromised, broken, or speculative plan.\n");
    out.push_str("   - You MUST set `status: \"blocked\"`, provide empty `items: []`, and document a comprehensive, rigorous technical explanation in `reason` detailing the exact contradiction, codebase evidence, and recommended developer action.\n\n");
    out.push_str("3. Step Granularity, Grouping and Compilability Invariants:\n");
    out.push_str("   - Execution Lifecycle Contract: EVERY leaf step is executed in an isolated turn with its own toolchain verification gates (check, clippy, test).\n");
    out.push_str("   - Avoid Micro-Fragmentation: Strictly avoid splitting adjacent, closely related edits into separate microscopic steps (e.g. adding a type and its immediate handler, or updating a module and its registration). Group cohesive changes across 1-4 related files under a single leaf step if they form a logical unit of work and carry no risk of patch conflicts.\n");
    out.push_str("   - Avoid Unmanageable Monoliths: Do not bundle 10-20 unrelated files into a single step; keep each leaf step calibrated to a cohesive unit (targeting 150-400 lines of change).\n");
    out.push_str("   - Compilability Invariant: The codebase MUST remain in a compiling, fully verified state at the end of EVERY leaf step. Never create broken intermediate steps.\n");
    out.push_str("   - Order steps strictly by prerequisite dependencies.\n");
    out.push_str("   - The plan hierarchy supports up to 5 levels of nesting. Leaf steps at the 5th level must not contain sub-items.\n\n");
    out.push_str("4. Strict Language Consistency Invariant:\n");
    out.push_str("   - Detect the primary natural language used in the plan's title and description.\n");
    out.push_str("   - You MUST formulate all titles, step details, explanations, and reasons strictly in that SAME natural language.\n");
    out.push_str("   - Do NOT switch languages unless the plan itself is written in that language.\n\n");
    out.push_str("5. Output Format:\n");
    out.push_str("   - Output strictly according to the specified JSON schema.\n\n");
    out.push_str("6. Codebase Exploration & Discovery Contract:\n");
    out.push_str("   - You have access to symbol contours in `<repo_map>` and already loaded files in `Active Context Files`.\n");
    out.push_str("   - If you need to inspect exact implementations, contracts, existing toolchains, or interfaces before designing the roadmap, set `status: \"needs_context\"`, specify the repository-relative file paths in `context_requests: [...]`, leave `items: []`, and explain in `explanation` what you are analyzing and why these files are required.\n");
    out.push_str("   - When all required context files are loaded, set `status: \"success\"` (or `status: \"blocked\"` if blockers found), set `context_requests: []`, and provide the decomposed `items`.\n");
    out
}

/// Builds the user prompt for deep plan refinement, incorporating context files and repo map.
pub fn build_plan_refine_user_prompt(
    plan: &Plan,
    context_files: &[ContextFileContent],
    repo_map: Option<&str>,
    instructions: Option<&str>,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Deep Plan Refinement: [{}] {}\n\n", plan.id, plan.title));

    if let Some(desc) = &plan.description {
        let trimmed = desc.trim();
        if !trimmed.is_empty() {
            out.push_str("## High-Level Architectural Intent (\"What\"):\n");
            out.push_str(trimmed);
            out.push_str("\n\n");
        }
    }

    if let Some(ins) = instructions {
        let trimmed = ins.trim();
        if !trimmed.is_empty() {
            out.push_str("## Developer Refinement Directives:\n");
            out.push_str(trimmed);
            out.push_str("\n\n");
        }
    }

    out.push_str("## Current Plan Draft:\n");
    if let Some(active_fmt) = format_active_plan_context(plan) {
        out.push_str(&active_fmt);
        out.push_str("\n\n");
    } else {
        out.push_str("*(No initial steps defined)*\n\n");
    }

    if let Some(rm) = repo_map {
        let trimmed = rm.trim();
        if !trimmed.is_empty() {
            out.push_str("## Codebase Symbol Contours (<repo_map>):\n");
            out.push_str(trimmed);
            out.push_str("\n\n");
        }
    }

    if !context_files.is_empty() {
        out.push_str("## Active Context Files:\n");
        for file in context_files {
            out.push_str(&format!("### File: `{}`\n```\n{}\n```\n\n", file.path, file.content));
        }
    }

    out.push_str("## Architect Instructions:\n");
    out.push_str("1. Conduct deep technical dependency analysis using the codebase contours and context files.\n");
    out.push_str("2. If you need to inspect specific file implementations before decomposing the plan, request them by setting `status: \"needs_context\"` with `context_requests: [\"path/to/file\"]` and empty `items: []`.\n");
    out.push_str("3. Check for any blockers, circular dependencies, or contradictions. If blocked, report `status: \"blocked\"` with exact `reason`.\n");
    out.push_str("4. If viable, decompose the plan into actionable, dependency-ordered leaf steps with `status: \"todo\"`. Calibrate leaf step granularity to cohesive units: group closely related adjacent edits together under one step to avoid micro-fragmentation, while avoiding monolithic multi-file dumps.\n");
    out.push_str("5. Language Directive: Detect the natural language of the plan title and description. Formulate all titles, details, explanations, and reasons strictly in that same language.\n");

    out
}

pub const PLAN_STEP_EXECUTION_PREFIX: &str = "# Target Plan Step Execution:";

pub use tauqe_protocol::plan::{
    format_plan_discussion_prompt, is_plan_discussion_prompt, PLAN_DISCUSSION_PREFIX,
};

/// Target plan and step identifiers parsed from an isolated plan step execution prompt.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlanStepTarget {
    pub plan_id: Option<String>,
    pub step_id: String,
}

/// Returns true if the prompt represents an isolated plan step execution turn.
pub fn is_plan_step_execution_prompt(prompt: &str) -> bool {
    prompt.starts_with(PLAN_STEP_EXECUTION_PREFIX)
}

/// Extracts the target plan ID and step ID from an isolated plan step execution prompt.
pub fn extract_plan_step_execution_target(prompt: &str) -> Option<PlanStepTarget> {
    if !prompt.starts_with(PLAN_STEP_EXECUTION_PREFIX) {
        return None;
    }
    let rest = prompt.strip_prefix(PLAN_STEP_EXECUTION_PREFIX)?.trim_start();
    if let Some(rest) = rest.strip_prefix('[') {
        let (spec, _) = rest.split_once(']')?;
        let spec = spec.trim();
        if spec.is_empty() {
            return None;
        }
        if let Some((plan_id, step_id)) = spec.split_once(':') {
            let plan_id = plan_id.trim();
            let step_id = step_id.trim();
            if !step_id.is_empty() {
                return Some(PlanStepTarget {
                    plan_id: if plan_id.is_empty() { None } else { Some(plan_id.to_string()) },
                    step_id: step_id.to_string(),
                });
            }
        } else {
            return Some(PlanStepTarget {
                plan_id: None,
                step_id: spec.to_string(),
            });
        }
    }
    None
}

/// Extracts the target step ID from an isolated plan step execution prompt.
pub fn extract_plan_step_execution_id(prompt: &str) -> Option<String> {
    extract_plan_step_execution_target(prompt).map(|t| t.step_id)
}

/// Formats a targeted prompt for executing a specific leaf step of a plan in isolation.
///
/// Excludes unrelated chat history and focuses the model entirely on completing
/// the designated step, while providing architectural plan context and completed prerequisites.
/// Formats a targeted prompt for executing a specific leaf step of a plan in isolation using default monotonic discovery.
pub fn format_plan_step_execution_prompt(
    plan: &Plan,
    step_id: &str,
    marker_suffix: &str,
) -> Result<String, String> {
    format_plan_step_execution_prompt_with_mode(
        plan,
        step_id,
        marker_suffix,
        crate::config::DiscoveryMode::Monotonic,
    )
}

/// Formats a targeted prompt for executing a specific leaf step of a plan in isolation with an explicit discovery strategy.
pub fn format_plan_step_execution_prompt_with_mode(
    plan: &Plan,
    step_id: &str,
    marker_suffix: &str,
    discovery_mode: crate::config::DiscoveryMode,
) -> Result<String, String> {
    let step = plan
        .find_item(step_id)
        .ok_or_else(|| format!("Step '{}' not found in plan '{}'", step_id, plan.id))?;

    if !step.is_leaf() {
        return Err(format!(
            "Step '{}' ({}) is not a leaf task; execute individual sub-items instead",
            step.id, step.title
        ));
    }

    let mut out = String::new();
    out.push_str(&format!(
        "{} [{}:{}] {}\n\n",
        PLAN_STEP_EXECUTION_PREFIX, plan.id, step.id, step.title
    ));

    out.push_str(&format!("## Plan: {}\n", plan.title));
    if let Some(desc) = &plan.description {
        let trimmed = desc.trim();
        if !trimmed.is_empty() {
            out.push_str(&format!("{}\n\n", trimmed));
        }
    }

    let mut completed_items = Vec::new();
    fn collect_completed<'a>(items: &'a [PlanItem], acc: &mut Vec<(&'a str, &'a str)>) {
        for item in items {
            if item.status == PlanItemStatus::Done {
                acc.push((&item.id, &item.title));
            }
            collect_completed(&item.children, acc);
        }
    }
    collect_completed(&plan.items, &mut completed_items);

    if !completed_items.is_empty() {
        out.push_str("### Already Completed Prerequisites:\n");
        for (id, title) in completed_items {
            out.push_str(&format!("- [x] #{} {}\n", id, title));
        }
        out.push('\n');
    }

    out.push_str("### Target Step to Implement:\n");
    out.push_str(&format!("- **ID**: `{}`\n", step.id));
    out.push_str(&format!("- **Title**: {}\n", step.title));
    if let Some(details) = &step.details {
        let trimmed = details.trim();
        if !trimmed.is_empty() {
            out.push_str(&format!("- **Details**:\n{}\n", trimmed));
        }
    }
    out.push('\n');

    out.push_str("## Execution Directives:\n");
    out.push_str(&format!(
        "1. Focus STRICTLY and EXCLUSIVELY on implementing step `{}`.\n",
        step.id
    ));
    out.push_str("2. Do NOT implement any upcoming or subsequent steps from the plan.\n");
    out.push_str("3. Keep changes minimal, coherent, and verified with toolchain checks.\n");
    out.push_str(&format!(
        "4. When implementation and verification are complete, emit the completion tag: <plan_step_done{0} /> (optionally with note=\"...\").\n",
        marker_suffix
    ));

    match discovery_mode {
        crate::config::DiscoveryMode::Monotonic => {
            out.push_str(&format!(
                "5. Discovery Phase: If you need to inspect or edit files listed in <repo_map> that are not yet loaded in <context>, request them immediately using <context_request{0} path=\"...\" access=\"read_only|editable\" /> before writing code or explanations. Request all necessary files together in a single turn to avoid exhausting discovery rounds. Do NOT halt with conversational text if the necessary files can simply be requested.\n",
                marker_suffix
            ));
        }
        crate::config::DiscoveryMode::Incremental => {
            out.push_str(&format!(
                "5. Discovery Phase (Incremental Strategy): If you need to inspect or edit files listed in <repo_map> that are not yet loaded in <context>, request them immediately using <context_request{0} path=\"...\" access=\"read_only|editable\" /> before writing code or explanations. If any loaded auto-context files turn out to be irrelevant or misleading, release them immediately using <context_drop{0} path=\"...\" /> to preserve token budget. Request all necessary files together in a single turn to avoid exhausting discovery rounds. Do NOT halt with conversational text if the necessary files can simply be requested.\n",
                marker_suffix
            ));
        }
        crate::config::DiscoveryMode::Snapshot => {
            out.push_str(&format!(
                "5. Discovery Phase (Snapshot Strategy): If you need to inspect or edit files listed in <repo_map> that are not yet loaded in <context>, request them immediately using <context_request{0} path=\"...\" access=\"read_only|editable\" /> before writing code or explanations. In each discovery round, your requests MUST specify the entire active working set of auto-context files required for this step; any auto-context files omitted from your requests will be automatically evicted from context. Do NOT halt with conversational text if the necessary files can simply be requested.\n",
                marker_suffix
            ));
        }
    }

    out.push_str("6. If you encounter an unsolvable blocking issue or need developer architectural decisions, explain it in text and DO NOT emit the completion tag.\n");

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    fn sample_plan() -> Plan {
        Plan {
            id: "jwt-auth".to_string(),
            title: "JWT Authentication".to_string(),
            description: Some("Implement secure tokens".to_string()),
            created_at: 100,
            updated_at: 200,
            items: vec![
                PlanItem {
                    id: "1".to_string(),
                    title: "Models".to_string(),
                    details: Some("Claims struct".to_string()),
                    status: PlanItemStatus::Done,
                    ..Default::default()
                },
                PlanItem {
                    id: "2".to_string(),
                    title: "Endpoint".to_string(),
                    details: Some("Write handler".to_string()),
                    status: PlanItemStatus::InProgress,
                    ..Default::default()
                },
            ],
        }
    }

    #[test]
    fn test_format_active_plan_context() {
        let formatted = format_active_plan_context(&sample_plan()).unwrap();
        assert!(formatted.contains("<active_plan id=\"jwt-auth\""));
        assert!(formatted.contains("progress=\"1/2 completed\""));
        assert!(formatted.contains("Endpoint (id: \"2\", status: IN_PROGRESS): Write handler"));
    }

    #[test]
    fn test_format_plan_step_execution_prompt() {
        let plan = sample_plan();

        let prompt = format_plan_step_execution_prompt(&plan, "2", "_XYZ").unwrap();
        assert!(prompt.contains("Target Plan Step Execution: [jwt-auth:2] Endpoint"));
        assert!(prompt.contains("Already Completed Prerequisites:"));

        let target = extract_plan_step_execution_target(&prompt).unwrap();
        assert_eq!(target.plan_id.as_deref(), Some("jwt-auth"));
        assert_eq!(target.step_id, "2");
        assert!(prompt.contains("- [x] #1 Models"));
        assert!(prompt.contains("- **ID**: `2`"));
        assert!(prompt.contains("<plan_step_done_XYZ />"));
        assert!(!prompt.contains("<context_drop_XYZ"));

        let inc_prompt = format_plan_step_execution_prompt_with_mode(
            &plan,
            "2",
            "_XYZ",
            crate::config::DiscoveryMode::Incremental,
        )
        .unwrap();
        assert!(inc_prompt.contains("Incremental Strategy"));
        assert!(inc_prompt.contains("<context_drop_XYZ"));

        let snap_prompt = format_plan_step_execution_prompt_with_mode(
            &plan,
            "2",
            "_XYZ",
            crate::config::DiscoveryMode::Snapshot,
        )
        .unwrap();
        assert!(snap_prompt.contains("Snapshot Strategy"));
        assert!(snap_prompt.contains("entire active working set"));
    }

    #[test]
    fn test_plan_refine_prompts_and_schema() {
        let plan = sample_plan();
        let sys = build_plan_refine_system_prompt(&plan);
        assert!(sys.contains("Strict Prohibition of Conceptual Drift"));
        assert!(sys.contains("Strict Blocker Protocol"));
        assert!(sys.contains("Compilability Invariants"));

        let ctx_files = vec![ContextFileContent {
            path: "crates/core/src/lib.rs".to_string(),
            content: "pub fn init() {}".to_string(),
            access: tauqe_protocol::ContextAccess::ReadOnly,
        }];
        let user_prompt = build_plan_refine_user_prompt(
            &plan,
            &ctx_files,
            Some("fn generate_token()"),
            Some("Focus on EdDSA"),
        );
        assert!(user_prompt.contains("# Deep Plan Refinement: [jwt-auth] JWT Authentication"));
        assert!(user_prompt.contains("Focus on EdDSA"));
        assert!(user_prompt.contains("crates/core/src/lib.rs"));
        assert!(user_prompt.contains("fn generate_token()"));

        let schema = plan_refine_response_schema();
        assert!(schema.get("properties").is_some());
        assert!(!schema.to_string().contains("$ref"), "Schema must not contain recursive $ref");
        let def = plan_refine_response_schema_definition();
        assert_eq!(def["name"], "plan_refinement");

        let raw_success = r#"{
            "status": "success",
            "explanation": "Decomposed into model and endpoint steps",
            "reason": null,
            "items": [
                {
                    "id": "1",
                    "title": "Model definition",
                    "details": "JWT claims struct",
                    "status": "todo",
                    "children": []
                }
            ]
        }"#;
        let parsed = parse_plan_refinement_output(raw_success).unwrap();
        assert_eq!(parsed.status, "success");
        assert_eq!(parsed.items.len(), 1);
        assert_eq!(parsed.items[0].id, "1");

        let raw_blocked = r#"```json
        {
            "status": "blocked",
            "explanation": "Cannot proceed",
            "reason": "Missing cryptographic library in cargo dependencies",
            "context_requests": [],
            "items": []
        }
        ```"#;
        let parsed_blocked = parse_plan_refinement_output(raw_blocked).unwrap();
        assert_eq!(parsed_blocked.status, "blocked");
        assert_eq!(
            parsed_blocked.reason.as_deref(),
            Some("Missing cryptographic library in cargo dependencies")
        );
        assert!(parsed_blocked.items.is_empty());

        let raw_needs_ctx = r#"{
            "status": "needs_context",
            "explanation": "Need to inspect toolchain module",
            "reason": null,
            "context_requests": ["crates/core/src/toolchain.rs"],
            "items": []
        }"#;
        let parsed_ctx = parse_plan_refinement_output(raw_needs_ctx).unwrap();
        assert_eq!(parsed_ctx.status, "needs_context");
        assert_eq!(parsed_ctx.context_requests, vec!["crates/core/src/toolchain.rs"]);
        assert!(parsed_ctx.items.is_empty());

        let raw_deep = r#"{
            "status": "success",
            "explanation": "Deep 5-level decomposition",
            "reason": null,
            "items": [
                {
                    "id": "1",
                    "title": "Level 1",
                    "details": null,
                    "status": "todo",
                    "children": [
                        {
                            "id": "1.1",
                            "title": "Level 2",
                            "details": null,
                            "status": "todo",
                            "children": [
                                {
                                    "id": "1.1.1",
                                    "title": "Level 3",
                                    "details": null,
                                    "status": "todo",
                                    "children": [
                                        {
                                            "id": "1.1.1.1",
                                            "title": "Level 4",
                                            "details": null,
                                            "status": "todo",
                                            "children": [
                                                {
                                                    "id": "1.1.1.1.1",
                                                    "title": "Level 5",
                                                    "details": null,
                                                    "status": "todo"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }"#;
        let parsed_deep = parse_plan_refinement_output(raw_deep).unwrap();
        assert_eq!(
            parsed_deep.items[0].children[0].children[0].children[0].children[0].id,
            "1.1.1.1.1"
        );
        assert!(parsed_deep.items[0].children[0].children[0].children[0].children[0].is_leaf());
    }

    #[test]
    fn test_format_plan_discussion_prompt() {
        let plan = sample_plan();

        let prompt = format_plan_discussion_prompt(&plan, &["2".to_string()], "Should we use EdDSA?");
        assert!(prompt.contains("# Plan Discussion: [jwt-auth] JWT Authentication"));
        assert!(prompt.contains("Implement secure tokens"));
        assert!(prompt.contains("<active_plan id=\"jwt-auth\""));
        assert!(prompt.contains("Items Focused by User for Discussion:"));
        assert!(prompt.contains("- **#2 Endpoint**"));
        assert!(prompt.contains("Should we use EdDSA?"));
        assert!(prompt.contains("Instructions for Model:"));
    }
}
