use anyhow::{bail, Context, Result};
use std::path::Path;
use tauqe_protocol::GitUndoResult;

use super::cmd::{commit_with_developer_author, run_git, stage_files};

pub const TAUQE_CO_AUTHOR_TRAILER: &str = "Co-authored-by: Tauqe AI <noreply@tauqe.dev>";
pub const CHECKPOINT_PREFIX: &str = "tauqe-checkpoint:";
pub const STEP_PREFIX: &str = "tauqe-step:";

/// Checks whether a commit was generated or co-authored by Tauqe AI.
pub fn is_tauqe_commit(subject: &str, body: &str, author: &str, trailers: &str) -> bool {
    trailers.contains("Tauqe AI")
        || trailers.contains("noreply@tauqe.dev")
        || body.contains(TAUQE_CO_AUTHOR_TRAILER)
        || body.contains("Co-authored-by: Tauqe AI")
        || body.contains("Generated by Tauqe AI")
        || author.contains("Tauqe AI")
        || author.contains("ai@tauqe.dev")
        || subject.starts_with("AI:")
        || subject.starts_with(STEP_PREFIX)
}

/// Checkpoint information representing saved pre-edit developer state.
#[derive(Debug, Clone)]
pub struct CheckpointInfo {
    pub created_checkpoint_commit: bool,
    pub previous_head: String,
}

/// Unwinds a temporary checkpoint commit at HEAD if present via mixed reset.
/// Returns true if a checkpoint commit was unwound.
pub fn unwind_checkpoint_if_present(dir: &Path) -> Result<bool> {
    let head_subject = run_git(Some(dir), &["log", "-1", "--format=%s"])
        .unwrap_or_default()
        .trim()
        .to_string();
    if head_subject.starts_with(CHECKPOINT_PREFIX) {
        run_git(Some(dir), &["reset", "HEAD~1"])
            .context("Failed to unwind temporary checkpoint commit")?;
        Ok(true)
    } else {
        Ok(false)
    }
}

/// Recovers repository state from an interrupted/crashed workflow:
/// 1. Unwinds any dangling intermediate step commits (tauqe-step:).
/// 2. Unwinds any temporary checkpoint commit (tauqe-checkpoint:), restoring
///    uncommitted developer changes safely into the working tree.
pub fn recover_interrupted_workflow(dir: &Path) -> Result<Option<String>> {
    if !crate::git::state::is_git_repository(Some(dir)) {
        return Ok(None);
    }

    let mut unwound_steps = 0;
    loop {
        let head_subject = run_git(Some(dir), &["log", "-1", "--format=%s"])
            .unwrap_or_default()
            .trim()
            .to_string();
        if head_subject.starts_with(STEP_PREFIX) {
            run_git(Some(dir), &["reset", "--hard", "HEAD~1"])
                .context("Failed to unwind dangling tauqe-step commit")?;
            unwound_steps += 1;
        } else {
            break;
        }
    }

    let unwound_checkpoint = unwind_checkpoint_if_present(dir)?;

    if unwound_steps > 0 || unwound_checkpoint {
        let msg = format!(
            "Recovered interrupted workflow: unwound {} step commit(s), restored checkpoint: {}",
            unwound_steps, unwound_checkpoint
        );
        Ok(Some(msg))
    } else {
        Ok(None)
    }
}

/// Creates a safe checkpoint of uncommitted changes before applying AI modifications.
pub fn create_checkpoint(dir: &Path) -> Result<CheckpointInfo> {
    let head = run_git(Some(dir), &["rev-parse", "HEAD"])
        .unwrap_or_else(|_| "HEAD".to_string())
        .trim()
        .to_string();

    let status = run_git(Some(dir), &["status", "--porcelain"]).unwrap_or_default();
    let is_dirty = !status.trim().is_empty();

    if !is_dirty {
        return Ok(CheckpointInfo {
            created_checkpoint_commit: false,
            previous_head: head,
        });
    }

    // Stage and commit uncommitted user changes into a checkpoint commit
    run_git(Some(dir), &["add", "-A"])
        .context("Failed to stage uncommitted changes for checkpoint")?;

    commit_with_developer_author(dir, "tauqe-checkpoint: uncommitted user changes", false)?;

    let new_head = run_git(Some(dir), &["rev-parse", "HEAD"])
        .unwrap_or_default()
        .trim()
        .to_string();

    Ok(CheckpointInfo {
        created_checkpoint_commit: true,
        previous_head: new_head,
    })
}

/// Restores working tree back to pre-checkpoint state (used on workflow failure/cancellation).
pub fn restore_checkpoint(dir: &Path, checkpoint: &CheckpointInfo) -> Result<()> {
    // 1. Reset working tree to checkpoint base commit
    run_git(Some(dir), &["reset", "--hard", &checkpoint.previous_head])?;
    let _ = run_git(Some(dir), &["clean", "-fd"]);

    // 2. If a checkpoint commit was created, unwind it so user modifications are restored
    if checkpoint.created_checkpoint_commit {
        let _ = unwind_checkpoint_if_present(dir)?;
    }
    Ok(())
}

/// Creates an intermediate step commit during edit execution or verification auto-healing.
pub fn create_step_commit(dir: &Path, changed_files: &[String], step_name: &str) -> Result<String> {
    if changed_files.is_empty() {
        return Ok(String::new());
    }

    stage_files(dir, changed_files)?;

    let commit_message = format!("tauqe-step: {}\n\n{}", step_name.trim(), TAUQE_CO_AUTHOR_TRAILER);
    commit_with_developer_author(dir, &commit_message, false)?;

    let short_hash = run_git(Some(dir), &["rev-parse", "--short", "HEAD"])?
        .trim()
        .to_string();

    Ok(short_hash)
}

/// Squashes all intermediate step commits into a single final AI commit.
pub fn finalize_ai_commit(
    dir: &Path,
    checkpoint: &CheckpointInfo,
    changed_files: &[String],
    summary: &str,
) -> Result<String> {
    if changed_files.is_empty() {
        bail!("No changed files to commit");
    }

    // 1. Soft-reset back to checkpoint base
    run_git(Some(dir), &["reset", "--soft", &checkpoint.previous_head])
        .context("Failed to soft reset to checkpoint base")?;

    // 2. If checkpoint commit was created, unwind it so user uncommitted changes stay in working tree
    if checkpoint.created_checkpoint_commit {
        let _ = unwind_checkpoint_if_present(dir)?;
    }

    // 3. Stage touched files
    stage_files(dir, changed_files)?;

    let commit_message = format!("{}\n\n{}", summary.trim(), TAUQE_CO_AUTHOR_TRAILER);
    commit_with_developer_author(dir, &commit_message, false)?;

    let short_hash = run_git(Some(dir), &["rev-parse", "--short", "HEAD"])?
        .trim()
        .to_string();

    Ok(short_hash)
}

/// Creates an isolated AI commit containing only the files modified by the model.
pub fn create_ai_commit(dir: &Path, changed_files: &[String], summary: &str) -> Result<String> {
    if changed_files.is_empty() {
        bail!("No changed files to commit");
    }

    // If HEAD is a temporary checkpoint commit, unwind it so user dirty changes remain in working tree
    let _ = unwind_checkpoint_if_present(dir)?;

    stage_files(dir, changed_files)?;

    let commit_message = format!("{}\n\n{}", summary.trim(), TAUQE_CO_AUTHOR_TRAILER);
    commit_with_developer_author(dir, &commit_message, false)?;

    let short_hash = run_git(Some(dir), &["rev-parse", "--short", "HEAD"])?
        .trim()
        .to_string();

    Ok(short_hash)
}

/// Undoes the last AI commit deterministically.
pub fn undo_last_ai_commit(dir: &Path) -> Result<GitUndoResult> {
    // 1. Verify that HEAD exists and is an AI commit
    let head_hash = run_git(Some(dir), &["rev-parse", "--short", "HEAD"])?
        .trim()
        .to_string();
    let author = run_git(Some(dir), &["log", "-1", "--format=%an <%ae>"])?
        .trim()
        .to_string();
    let subject = run_git(Some(dir), &["log", "-1", "--format=%s"])?
        .trim()
        .to_string();

    let body = run_git(Some(dir), &["log", "-1", "--format=%b"]).unwrap_or_default();
    let trailers = run_git(
        Some(dir),
        &["log", "-1", "--format=%(trailers:key=Co-authored-by)"],
    )
    .unwrap_or_default();

    let is_ai_commit = is_tauqe_commit(&subject, &body, &author, &trailers);

    if !is_ai_commit {
        bail!(
            "HEAD commit {} ('{}') was not created by Tauqe AI. Undo refused for safety.",
            head_hash,
            subject
        );
    }

    // 2. Identify files changed in this AI commit before unwinding
    let touched_output = run_git(
        Some(dir),
        &["diff-tree", "--no-commit-id", "--name-only", "-r", "HEAD"],
    )
    .unwrap_or_default();
    let touched_files: Vec<String> = touched_output
        .lines()
        .map(|l| l.trim().to_string())
        .filter(|l| !l.is_empty())
        .collect();

    // 3. Mixed reset to HEAD~1
    run_git(Some(dir), &["reset", "HEAD~1"]).context("Failed to reset AI commit")?;

    // 4. Revert only the touched files in the working tree to the new HEAD
    for file in &touched_files {
        let exists_in_head =
            run_git(Some(dir), &["cat-file", "-e", &format!("HEAD:{}", file)]).is_ok();
        if exists_in_head {
            let _ = run_git(Some(dir), &["checkout", "HEAD", "--", file]);
        } else {
            let full = dir.join(file);
            let _ = std::fs::remove_file(&full);
        }
    }

    // 5. Check if previous commit was a checkpoint commit
    let restored_checkpoint = unwind_checkpoint_if_present(dir)?;

    let new_head = run_git(Some(dir), &["rev-parse", "--short", "HEAD"])
        .unwrap_or_else(|_| "HEAD".to_string())
        .trim()
        .to_string();

    let msg = if restored_checkpoint {
        format!(
            "Undid AI commit {} ('{}') and restored original uncommitted changes.",
            head_hash, subject
        )
    } else {
        format!("Undid AI commit {} ('{}').", head_hash, subject)
    };

    Ok(GitUndoResult {
        undone_commit: head_hash,
        restored_checkpoint,
        new_head,
        message: msg,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn test_recover_interrupted_workflow_clean_repo() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path();
        crate::git::state::init_repository(Some(path), true).unwrap();

        let recovery = recover_interrupted_workflow(path).unwrap();
        assert!(recovery.is_none());
    }

    #[test]
    fn test_recover_interrupted_workflow_with_checkpoint_and_steps() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path();
        crate::git::state::init_repository(Some(path), true).unwrap();

        // Simulate user uncommitted changes
        let user_file = path.join("user_work.txt");
        fs::write(&user_file, "original uncommitted work").unwrap();

        // 1. Checkpoint created
        let chk = create_checkpoint(path).unwrap();
        assert!(chk.created_checkpoint_commit);

        // 2. Step commit created
        let ai_file = path.join("ai_work.txt");
        fs::write(&ai_file, "ai step modification").unwrap();
        create_step_commit(path, &["ai_work.txt".to_string()], "apply step 1").unwrap();

        // 3. Crash recovery runs
        let recovery = recover_interrupted_workflow(path).unwrap();
        assert!(recovery.is_some());
        let msg = recovery.unwrap();
        assert!(msg.contains("unwound 1 step commit(s)"));
        assert!(msg.contains("restored checkpoint: true"));

        // User uncommitted work must be intact in the working tree
        assert!(user_file.exists());
        assert_eq!(fs::read_to_string(&user_file).unwrap(), "original uncommitted work");
        // Intermediate step modification should be removed
        assert!(!ai_file.exists());
    }
}
